services:
  db:
    image: postgres:16
    container_name: opsflow-db
    environment:
      POSTGRES_DB: opsflow
      POSTGRES_USER: opsflow
      POSTGRES_PASSWORD: opsflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: opsflow-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/opsflow
      SPRING_DATASOURCE_USERNAME: opsflow
      SPRING_DATASOURCE_PASSWORD: opsflow

volumes:
  pgdata:
